// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqrQXykMsM7dUy-xoZCyFb9PLDeKFQcQ',
    appId: '1:407012303842:android:064037877d1625ba41cfbb',
    messagingSenderId: '407012303842',
    projectId: 'catatuang-868a1',
    databaseURL: 'https://catatuang-868a1-default-rtdb.firebaseio.com',
    storageBucket: 'catatuang-868a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8QyzfU6rQuiec-1orKjMS_qIJkLeaN9U',
    appId: '1:407012303842:ios:5b73d40e7df0cc7541cfbb',
    messagingSenderId: '407012303842',
    projectId: 'catatuang-868a1',
    databaseURL: 'https://catatuang-868a1-default-rtdb.firebaseio.com',
    storageBucket: 'catatuang-868a1.appspot.com',
    androidClientId: '407012303842-hjqtj6o7f9aaq7uu8gi7qoh3h46btilp.apps.googleusercontent.com',
    iosClientId: '407012303842-j4fllliiduen8ssd6e5370lds702070v.apps.googleusercontent.com',
    iosBundleId: 'com.example.catatUang',
  );
}
